PRAGMA foreign_keys = ON;

-- CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
  CODI  CHAR(6)  PRIMARY KEY,
  DNI   CHAR(8),
  NOMB  VARCHAR(40),
  APEL  VARCHAR(40),
  TELF  VARCHAR(9),
  EMAIL VARCHAR(60),
  CALLE VARCHAR(40),
  DIST  VARCHAR(30),
  CIUD  VARCHAR(30)
);

-- EMPRESA
CREATE TABLE IF NOT EXISTS EMPRESA (
  EMPR  CHAR(5)  PRIMARY KEY,
  RUC   CHAR(11),
  RAZS  VARCHAR(60),
  CALLE VARCHAR(40),
  DIST  VARCHAR(30),
  CIUD  VARCHAR(30)
);

-- VENDEDOR
CREATE TABLE IF NOT EXISTS VENDEDOR (
  CODV  CHAR(5) PRIMARY KEY,
  NOMB  VARCHAR(40),
  APEL  VARCHAR(40)
);

-- PRODUCTO
CREATE TABLE IF NOT EXISTS PRODUCTO (
  CODT  CHAR(6) PRIMARY KEY,
  NOMB  VARCHAR(50),
  UNID  VARCHAR(10),
  PREC  DECIMAL(10,2)
);

-- FACTURA
CREATE TABLE IF NOT EXISTS FACTURA (
  NFAC    CHAR(10) PRIMARY KEY,
  FECEM   DATE,
  FECVEN  DATE,
  "DESC"  DECIMAL(10,2) DEFAULT 0,     -- descuento
  IGV     DECIMAL(10,2) DEFAULT 0,
  TOTFAC  DECIMAL(10,2) DEFAULT 0,
  CODI    CHAR(6)  NOT NULL,
  EMPR    CHAR(5)  NOT NULL DEFAULT 'E0001',
  CODV    CHAR(5)  NOT NULL,
  FOREIGN KEY (CODI) REFERENCES CLIENTE(CODI),
  FOREIGN KEY (EMPR) REFERENCES EMPRESA(EMPR),
  FOREIGN KEY (CODV) REFERENCES VENDEDOR(CODV)
);

-- DETALLE_FACTURA
CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
  NFAC    CHAR(10) NOT NULL,
  CODT    CHAR(6)  NOT NULL,
  CANT    INTEGER  NOT NULL,
  PRECLI  DECIMAL(10,2) NOT NULL,  -- precio en la línea (subtotal de ese item)
  PRIMARY KEY (NFAC, CODT),
  FOREIGN KEY (NFAC) REFERENCES FACTURA(NFAC) ON DELETE CASCADE,
  FOREIGN KEY (CODT) REFERENCES PRODUCTO(CODT)
);

-- Indices sugeridos
CREATE INDEX IF NOT EXISTS I_CODI  ON CLIENTE(CODI);
CREATE INDEX IF NOT EXISTS I_DNI   ON CLIENTE(DNI);
CREATE INDEX IF NOT EXISTS I_EMPR  ON EMPRESA(EMPR);
CREATE INDEX IF NOT EXISTS I_RUC   ON EMPRESA(RUC);
CREATE INDEX IF NOT EXISTS I_CODV  ON VENDEDOR(CODV);
CREATE INDEX IF NOT EXISTS I_CODT  ON PRODUCTO(CODT);
CREATE INDEX IF NOT EXISTS I_NFAC  ON FACTURA(NFAC);
