PRAGMA foreign_keys = ON;

-- CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
  CODI  CHAR(6)      PRIMARY KEY,
  DNI   CHAR(8)      NOT NULL CHECK (length(DNI)=8 AND DNI GLOB '[0-9]*'),
  NOMB  VARCHAR(40)  NOT NULL,
  APEL  VARCHAR(40)  NOT NULL,
  TELF  VARCHAR(15),
  EMAIL VARCHAR(60),
  CALLE VARCHAR(40),
  DIST  VARCHAR(30),
  CIUD  VARCHAR(30),
  UNIQUE (DNI),
  UNIQUE (EMAIL),
  UNIQUE (TELF)

-- EMPRESA
CREATE TABLE IF NOT EXISTS EMPRESA (
  EMPR  CHAR(5)      PRIMARY KEY,
  RUC   CHAR(11)     NOT NULL CHECK (length(RUC)=11 AND RUC GLOB '[0-9]*'),
  RAZS  VARCHAR(60)  NOT NULL,
  CALLE VARCHAR(40),
  DIST  VARCHAR(30),
  CIUD  VARCHAR(30),
  UNIQUE (RUC)
);

-- VENDEDOR
CREATE TABLE IF NOT EXISTS VENDEDOR (
  CODV  CHAR(5)      PRIMARY KEY,
  NOMB  VARCHAR(40)  NOT NULL,
  APEL  VARCHAR(40)  NOT NULL
);

-- PRODUCTO
CREATE TABLE IF NOT EXISTS PRODUCTO (
  CODT  CHAR(6)      PRIMARY KEY,
  NOMB  VARCHAR(50)  NOT NULL,
  UNID  VARCHAR(10)  NOT NULL CHECK (length(UNID) BETWEEN 1 AND 10),
  PREC  DECIMAL(10,2) NOT NULL CHECK (PREC >= 0),
  UNIQUE (NOMB, UNID)
);

-- FACTURA
CREATE TABLE IF NOT EXISTS FACTURA (
  NFAC    CHAR(10)      PRIMARY KEY,
  FECEM   DATE,
  FECVEN  DATE,
  "DESC"  DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK("DESC" >= 0),
  IGV     DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK(IGV    >= 0),
  TOTFAC  DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK(TOTFAC >= 0),
  CODI    CHAR(6)  NOT NULL,
  EMPR    CHAR(5)  NOT NULL DEFAULT 'E0001',
  CODV    CHAR(5)  NOT NULL,
  FOREIGN KEY (CODI) REFERENCES CLIENTE(CODI),
  FOREIGN KEY (EMPR) REFERENCES EMPRESA(EMPR),
  FOREIGN KEY (CODV) REFERENCES VENDEDOR(CODV)
);

-- DETALLE_FACTURA
CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
  NFAC    CHAR(10) NOT NULL,
  CODT    CHAR(6)  NOT NULL,
  CANT    INTEGER  NOT NULL CHECK (CANT > 0),
  PRECLI  DECIMAL(10,2) NOT NULL CHECK (PRECLI >= 0),
  PRIMARY KEY (NFAC, CODT),
  FOREIGN KEY (NFAC) REFERENCES FACTURA(NFAC) ON DELETE CASCADE,
  FOREIGN KEY (CODT) REFERENCES PRODUCTO(CODT)
);

-- Indices sugeridos
CREATE INDEX IF NOT EXISTS I_CODI  ON CLIENTE(CODI);
CREATE UNIQUE INDEX IF NOT EXISTS I_DNI_UNQ   ON CLIENTE(DNI);
CREATE UNIQUE INDEX IF NOT EXISTS I_EMAIL_UNQ ON CLIENTE(EMAIL);
CREATE UNIQUE INDEX IF NOT EXISTS I_TELF_UNQ  ON CLIENTE(TELF);

CREATE INDEX IF NOT EXISTS I_EMPR  ON EMPRESA(EMPR);
CREATE UNIQUE INDEX IF NOT EXISTS I_RUC_UNQ   ON EMPRESA(RUC);

CREATE INDEX IF NOT EXISTS I_CODV  ON VENDEDOR(CODV);

CREATE INDEX IF NOT EXISTS I_CODT  ON PRODUCTO(CODT);
CREATE UNIQUE INDEX IF NOT EXISTS I_PROD_NOMB_UNID ON PRODUCTO(NOMB, UNID);

CREATE INDEX IF NOT EXISTS I_NFAC  ON FACTURA(NFAC);